### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [jean-merelis/liquibase-hibernate5#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/liquibase/ext/hibernate/snapshot/UniqueConstraintSnapshotGenerator.java: Line number => 116: API name => MessageDigest:Unexpected call to method reset on object of type java.security.MessageDigest. Expect a call to one of the following methods digest,update<BR>

**Comment by jean-merelis** [comment]
This project no longer receives maintenance.
Please use the official Liquibase library - https://github.com/liquibase/liquibase-hibernate
